### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by rjsgml5698** [intel-isl/Open3D-ML#134]
Is the following error unresolvable in **wsl2**?

```
(open3d) rjsgml5698@DESKTOP-BVT01B5:/mnt/c/Develop/d3d/open3d-ml/examples$ python visualize.py kitti '/mnt/f/kitti-dataset/'
2020-10-23 09:40:10.226722: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
INFO - 2020-10-23 09:40:11,427 - semantickitti - Found 19130 pointclouds for training
Segmentation fault
```

OS: [Ubuntu 20.04 on Windows 10(build version:1909)]
Python version:  3.6.12
Open3D version: 0.11.0(latest released) : conda install -c open3d-admin open3d

**Comment by benjaminum** [comment]
Does WSL 2 support OpenGL? Can you run glxgears or other software using OpenGL?

**Comment by rjsgml5698** [comment]
yes, It seems opengl is supported. However, the version of openGL is low. Is this the reason?

![image](https://user-images.githubusercontent.com/40594949/97124045-e5424180-1771-11eb-9e2d-a86aaaef0142.png)

**Comment by benjaminum** [comment]
> yes, It seems opengl is supported. However, the version of openGL is low. Is this the reason?

It could be. What is the output of glxinfo? Did running glxgears work?

**Comment by rjsgml5698** [comment]
> Did running glxgears work?

yes, It works fine.

**glxgears command:**
![image](https://user-images.githubusercontent.com/40594949/97143087-564f1c80-17a5-11eb-9914-150392e52ae5.png)

**output of glxinfo:**
![image](https://user-images.githubusercontent.com/40594949/97143178-85658e00-17a5-11eb-90dd-17cc659b83d9.png)

**output of glxinfo | grep OpenGL :**
![image](https://user-images.githubusercontent.com/40594949/97143210-9910f480-17a5-11eb-953b-40d8d569adeb.png)

**Comment by benjaminum** [comment]
Seems like a problem with the OpenGL version. The renderer we use (Filament) requires OpenGL 4.1 and that is probably the reason why the context creation fails. @errissa @prewettg does this make sense?

**Comment by rjsgml5698** [comment]
> glxinfo: ... **direct rendering : No (LIBGL_ALWAYS_INDIRECT set)** ...

I think openGL support is limited because rendering is done indirectly on wsl.

Thank you for you reply.

**Comment by rjsgml5698** [comment]
@benjaminum 

I solved it by adding

> export LIBGL_ALWAYS_INDIRECT=0

**Comment by benjaminum** [comment]
Thanks for letting us know!

**Comment by rjsgml5698** [comment]
@benjaminum 

Additionally,

> export LIBGL_ALWAYS_INDIRECT=0 **is limited to openGL version 3.3** 

As you mentioned,

> The renderer we use (Filament) requires OpenGL 4.1

Therefore, to change to version 4.1 or higher, We can do as follows.

```
sudo add-apt-repository ppa:kisak/kisak-mesa
sudo apt-get update
(wsl --shutdown and restart)
glxinfo | grep ":" 
```
(OpenGL 3.3 to 4.5)

I hope this helps you. Thank you for your effort.

![image](https://user-images.githubusercontent.com/40594949/97399573-be7e3980-1930-11eb-8be2-423a4ea1c0fe.png)

**Comment by benjaminum** [comment]
Thanks! 
WSL seems to get better and better. Maybe we should add this information to our documentation. What do you think about this @yxlao ?

**Comment by wangmiaowei** [comment]
@rjsgml5698 Thanks for your suggestions. But when I follow your steps, I did not upgrade my OpenGL which is still 3.1:
name of display: :0
NVD3D10: CPU cyclestats are disabled on client virtualization
NVD3D10: CPU cyclestats are disabled on client virtualization
display: :0  screen: 0
direct rendering: Yes
server glx vendor string: SGI
server glx version string: 1.4
server glx extensions:
client glx vendor string: Mesa Project and SGI
client glx version string: 1.4
client glx extensions:
GLX version: 1.4
GLX extensions:
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Microsoft Corporation (0xffffffff)
    Device: D3D12 (NVIDIA Quadro P2000 with Max-Q Design) (0xffffffff)
    Version: 21.1.3
    Accelerated: yes
    Video memory: 20160MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 3.3
    Max compat profile version: 3.1
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.0
OpenGL vendor string: Microsoft Corporation
OpenGL renderer string: D3D12 (NVIDIA Quadro P2000 with Max-Q Design)
OpenGL core profile version string: 3.3 (Core Profile) Mesa 21.1.3 - kisak-mesa PPA
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.1 Mesa 21.1.3 - kisak-mesa PPA
OpenGL shading language version string: 1.40
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 21.1.3 - kisak-mesa PPA
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
OpenGL ES profile extensions:
288 GLXFBConfigs:
Is there anythin related to Graphic Interface?
