### ISSUE TITLE
Error(s) in loading state_dict for RandLANet

### ISSUE THREAD

**Issue by umarkhancodes** [intel-isl/Open3D-ML#144]
I am trying to run a pretrained model from modelzoo for s3dis dataset. 
I downloaded the model from : 
https://storage.googleapis.com/open3d-releases/model-zoo/randlanet_s3dis_area5_202010091333utc.pth .

I used the following code (just like vis_pred.py) to use this model.

model = ml3d.models.RandLANet(ckpt_path=ckpt_path) #ckpt_path = path to the above downloaded model
pipeline_r = ml3d.pipelines.SemanticSegmentation(model)
pipeline_r.load_ckpt(model.cfg.ckpt_path)

I get the following error on the third statement  ( pipeline_r.load_ckpt(model.cfg.ckpt_path) ):

Error(s) in loading state_dict for RandLANet.

Kindly help me in this matter.

**Comment by sanskar107** [comment]
Model configuration used in pretrained models is different from default config.
For RandLANet on S3DIS, use `ml3d/configs/randlanet_s3dis.yml`.

**Comment by umarkhancodes** [comment]
@sanskar107  that's exactly what i thought about doing and i started testing this approach using randlanet on semantic kitty. 

I used the following code :
 
cfg_file= 'path to config file' 
cfg = _ml3d.utils.Config.load_from_file(cfg_file)
model = ml3d.models.RandLANet(**cfg.model)
pipeline = ml3d.pipelines.SemanticSegmentation(model, **cfg.pipeline)


well the model loads successfully but it does not gives the same (good) results on the demo_data input files. while the same model when loaded with default config gives much better results. 
So I though that i am maybe doing something wrong. 

can you kindly comment on this.

**Comment by YilingQiao** [comment]
Hi, Umar, thanks for your question. You mentioned that the model gives better results with default configs. What customized configs did you use that produced worse results?

**Comment by AmarR91** [comment]
I faced the same problem. What I have changed in configs is to set the dim_input to 3 (it was 8 before).
Kindly request help.

**Comment by YilingQiao** [comment]
Hi, I test with this script and it works. Please check whether you have downloaded checkpoints for other datasets. Maybe you need to delete the old one in case the script is using the wrong ckpt.

```
#!/usr/bin/env python
import open3d.ml.torch as ml3d
import argparse
import math
import numpy as np
import os
import random
import sys
import torch
import pandas as pd
from plyfile import PlyData, PlyElement
from os.path import exists, join, isfile, dirname, abspath, split

example_dir = os.path.dirname(os.path.realpath(__file__))


def get_custom_data(pc_names, path):
    pc_data = []
    for i, name in enumerate(pc_names):
        pc_path = join(path, 'points', name + '.ply')

        data = PlyData.read(pc_path)['vertex']

        point = np.zeros((data['x'].shape[0], 3), dtype=np.float32)
        point[:, 0] = data['x']
        point[:, 1] = data['y']
        point[:, 2] = data['z']

        feat = np.zeros(point.shape, dtype=np.float32)
        feat[:, 0] = data['red']
        feat[:, 1] = data['green']
        feat[:, 2] = data['blue']

        label = np.array(data['class'], dtype=np.int32).reshape((-1,))

        data = {
            'point': point,
            'feat': feat,
            'label': label,
        }
        pc_data.append(data)

    return pc_data


def pred_custom_data(pc_names, pcs, pipeline_r):
    vis_points = []
    for i, data in enumerate(pcs):
        name = pc_names[i]

        results_r = pipeline_r.run_inference(data)
        pred_label_r = (results_r['predict_labels'] + 1).astype(np.int32)
        # WARNING, THIS IS A HACK
        # Fill "unlabeled" value because predictions have no 0 values.
        pred_label_r[0] = 0

        label = data['label']
        pts = data['point']



        vis_d = {
            "name": name + "_randlanet",
            "points": pts,
            "labels": pred_label_r,
        }
        vis_points.append(vis_d)


    return vis_points


# ------------------------------
import open3d.ml as _ml3d

def main():
    semantic_labels = ml3d.datasets.Semantic3D.get_label_to_names()
    v = ml3d.vis.Visualizer()
    lut = ml3d.vis.LabelLUT()
    for val in sorted(semantic_labels.keys()):
        lut.add_label(semantic_labels[val], val)
    v.set_lut("pred", lut)

    randlanet_url = "https://storage.googleapis.com/open3d-releases/model-zoo/randlanet_s3dis_area5_202010091333utc.pth"

    ckpt_path = example_dir + "/vis_weights_{}.pth".format('RandLANet')
    if not exists(ckpt_path):
        cmd = "wget {} -O {}".format(randlanet_url, ckpt_path)
        os.system(cmd)
        
    cfg_file = "./ml3d/configs/randlanet_s3dis.yml"
    cfg = _ml3d.utils.Config.load_from_file(cfg_file)

    cfg.model.ckpt_path = ckpt_path

    model = ml3d.models.RandLANet(**cfg.model)
    pipeline = ml3d.pipelines.SemanticSegmentation(model, **cfg.pipeline)
    pipeline.load_ckpt(model.cfg.ckpt_path)

    data_path = example_dir + "/demo_data"
    pc_names = ["Area_1_hallway_7"]
    pcs = get_custom_data(pc_names, data_path)

    pcs_with_pred = pred_custom_data(pc_names, pcs, pipeline)

    v.visualize(pcs_with_pred) 


if __name__ == "__main__":
    main()

```
