### ISSUE TITLE
randlanet_toronto3D_202010091306.pth file download failed

### ISSUE THREAD

**Issue by aboutyy** [intel-isl/Open3D-ML#158]
`<Error>
<Code>AccessDenied</Code>
<Message>Access denied.</Message>
<Details>Anonymous caller does not have storage.objects.get access to the Google Cloud Storage object.</Details>
</Error>`

here are the code

**Comment by sanskar107** [comment]
Thanks for pointing it out. We've fixed the link, it should work now.

**Comment by aboutyy** [comment]
thanks it worked

**Comment by aboutyy** [comment]
> Thanks for pointing it out. We've fixed the link, it should work now.

thanks sanskar, it worked

**Comment by AmarR91** [comment]
The link is not working again. Can you please fix it?
