### ISSUE TITLE
semantic segmentation of point clouds

### ISSUE THREAD

**Issue by AmarR91** [intel-isl/Open3D-ML#165]
How can I use my own point clouds as input for the semantic segmenation process? Do I need to pre-process my point clouds and which format is generally required (npy / txt)? I would like to test the pre-trained models for this task. I would really appreciate any help.

**Comment by sanskar107** [comment]
You can use the `Custom3D` dataset class defined in `ml3d/datasets/customdataset.py` for loading your pointclouds. The assumed specification of the pointcloud is mentioned in the same file.

**Comment by AmarR91** [comment]
Thanks for the reply. I tried to follow the example in examples/vis_pred.py
What I don't get is why the demo_data folder contains label and point data. Why do I need both and how can I create label data for my own (raw) point cloud dataset? Sorry, I am new in this field.

**Comment by YilingQiao** [comment]
Could you try this for a single point cloud?
```
data = {
    'point': your_point, # your point cloud, an nx3 numpy array
    'label': np.zeros([your_point.shape[0]])
}
result = pipeline.run_inference(data)
```

Thanks for your suggestion. We will create a more convenient interface for inference-only data.

**Comment by AmarR91** [comment]
@YilingQiao Thanks for the hint. That helped me to compile the code.
