### ISSUE TITLE
Prepare my own dataset (ply to npy)

### ISSUE THREAD

**Issue by HollowHeartNet** [intel-isl/Open3D-ML#196]
As the input point cloud is expected to be in npy format (e.g. in vis_pred.py), I would like to know how to convert my own point cloud in .ply format into npy format (compatible with open3d-ml).

Any suggestions would be great. Thanks in advance!

**Comment by AmarR91** [comment]
Solved this issue by using the following code:

pcd_load = o3d.io.read_point_cloud('/path/to/point_cloud')
pcd_to_npy = np.asarray(pcd_load.points)
points = np.array(pcd_to_npy[:, :3], dtype=np.float32)
np.save('/output/path', points)

hope this will help somebody

**Comment by sanskar107** [comment]
@AmarR91 your third line `points = np.array(data[:, :3], dtype=np.float32)` limits second dimension to be 3. You can use `points = np.array(data, dtype=np.float32)` for retaining same dimension.
