### ISSUE TITLE
AssertionError: Wrong feature dimension, please update dim_input(3 + feature_dimension) in config

### ISSUE THREAD

**Issue by AmarR91** [intel-isl/Open3D-ML#204]
I've changed the code in examples/vis_pred.py to visualize the prediction for semantic3D using the pre-trained model.

The code was changed as follows:

    semantic_labels = ml3d.datasets.Semantic3D.get_label_to_names()
    v = ml3d.vis.Visualizer()
    lut = ml3d.vis.LabelLUT()
    for val in sorted(semantic_labels.keys()):
        lut.add_label(semantic_labels[val], val)
    v.set_lut("pred", lut)

    randlanet_url = "https://storage.googleapis.com/open3d-releases/model-zoo/randlanet_semantic3d_202012120312utc.pth"

    ckpt_path = example_dir + "/vis_weights_{}.pth".format('RandLANet')
    if not exists(ckpt_path):
        cmd = "wget {} -O {}".format(randlanet_url, ckpt_path)
        os.system(cmd)
        
    cfg_file = "/path/to/randlanet_semantic3d.yml"
    cfg = _ml3d.utils.Config.load_from_file(cfg_file)

    model = ml3d.models.RandLANet(**cfg.model)
    pipeline = ml3d.pipelines.SemanticSegmentation(model, **cfg.pipeline)
    pipeline.load_ckpt(model.cfg.ckpt_path)

    data_path = example_dir + "/demo_data"
    pc_names = ["bildstein_station1_xyz_intensity_rgb_float32"]
    pcs = get_custom_data(pc_names, data_path)
    
    pcs_with_pred = pred_custom_data(pc_names, pcs, pipeline)
	
    v.visualize(pcs_with_pred) 

_________

I haven't changed anything in randlanet_semantic3d.yml, just added the ckpt_path. That's it. 

When I run the code, I get the following error: 

"AssertionError: Wrong feature dimension, please update dim_input(3 + feature_dimension) in config"

I tried to changed the number of the dim_input in the yml file, but it didn't help since dim_input = 6 is needed for semantic3d. 

Kindly request help on this issue. 
Thanks in advance

**Comment by YilingQiao** [comment]
Hi, Amar! Thanks for your issue. Did you also change the input in `get_custom_data()`?
RandLANet will need the `feat` channel for  Semantic3D, so it cannot be `None`.

I change it like this and it works,

```
def get_custom_data(pc_names, path):
    pc_data = []
    for i, name in enumerate(pc_names):
        pc_path = join(path, 'points', name + '.txt')

        pc = pd.read_csv(pc_path,
                         header=None,
                         delim_whitespace=True,
                         dtype=np.float32).values

        point = pc[:, 0:3]
        feat = pc[:, [4, 5, 6]]
        intensity = pc[:, 3]

        label = np.zeros((point.shape[0],), dtype=np.int32)

        data = {
            'point': point,
            'feat': feat,
            'label': label,
        }
        pc_data.append(data)

    return pc_data
```

**Comment by AmarR91** [comment]
@YilingQiao Thank you very much. Now it works.
