### ISSUE TITLE
open3d ML support for windows

### ISSUE THREAD

**Issue by giants19** [intel-isl/Open3D-ML#205]
Thank you for your hard work for open3d ml. I am using windows 10.
An error "Open3D was not built with PyTorch support!" was returned when running as "import open3d.ml.torch as ml3d".
Open3d itself is working very well. 
Is open3d ML supported for windows as of Dec, 2020? If not, do you have any plans for windows support in the near future?

Thanks in advance

**Comment by benjaminum** [comment]
Hi @giants19 
Unfortunately, it is not supported right now. You could try to use the windows subsystem for linux (WSL) to access the functionality on win 10.
The plan is to enable all features on windows but there is no specific timeline yet.

**Comment by giants19** [comment]
Hi @benjaminum 
Thank you for your reply. Well noted. I will consider the option of WSL. 
Open3D library is very useful for me and thanks for your hard work for o3d.
