### ISSUE TITLE
How to use L515 to build a 3D model of an object with Open3D?

### ISSUE THREAD

**Issue by fireflying12** [intel-isl/Open3D-ML#207]
I would like to ask is there any Python coding example, which can operate the L515 to scan around an object and create a 3D model? The final exported product could be a point cloud model or a mesh model, point cloud model would be more preferable. Thank you.

**Comment by ssheorey** [comment]
Please see this tutorial: http://www.open3d.org/docs/latest/tutorial/sensor/realsense.html
