### ISSUE TITLE
 RuntimeError: Error(s) in loading state_dict for RandLANet

### ISSUE THREAD

**Issue by makaay2077** [intel-isl/Open3D-ML#216]
i ran the instructions here in 'google colab' but it failed 
https://github.com/intel-isl/Open3D-ML/blob/master/docs/howtos.md#visualize-network-predictions

INFO - 2021-01-29 11:09:29,809 - semantic_segmentation - Loading checkpoint ./logs/vis_weights_RandLANet.pth

---------------------------------------------------------------------------

RuntimeError                              Traceback (most recent call last)

<ipython-input-11-797c1efa3a21> in <module>()
     11 model = RandLANet(ckpt_path=ckpt_path)
     12 pipeline_r = SemanticSegmentation(model)
---> 13 pipeline_r.load_ckpt(model.cfg.ckpt_path)
     14 
     15 ckpt_path = "./logs/vis_weights_{}.pth".format('KPFCNN')

1 frames

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in load_state_dict(self, state_dict, strict)
   1043         if len(error_msgs) > 0:
   1044             raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
-> 1045                                self.__class__.__name__, "\n\t".join(error_msgs)))
   1046         return _IncompatibleKeys(missing_keys, unexpected_keys)
   1047 

RuntimeError: Error(s) in loading state_dict for RandLANet:
	Unexpected key(s) in state_dict: "Encoder_layer_4mlp1.biases", "Encoder_layer_4mlp1.weights", "Encoder_layer_4mlp1.conv.weight", "Encoder_layer_4mlp1.conv.bias", "Encoder_layer_4mlp1.batch_normalization.weight", "Encoder_layer_4mlp1.batch_normalization.bias", "Encoder_layer_4mlp1.batch_normalization.running_mean", "Encoder_layer_4mlp1.batch_normalization.running_var", "Encoder_layer_4mlp1.batch_normalization.num_batches_tracked", "Encoder_layer_4LFAmlp1.biases", "Encoder_layer_4LFAmlp1.weights", "Encoder_layer_4LFAmlp1.conv.weight", "Encoder_layer_4LFAmlp1.conv.bias", "Encoder_layer_4LFAmlp1.batch_normalization.weight", "Encoder_layer_4LFAmlp1.batch_normalization.bias", "Encoder_layer_4LFAmlp1.batch_normalization.running_mean", "Encoder_layer_4LFAmlp1.batch_normalization.running_var", "Encoder_layer_4LFAmlp1.batch_normalization.num_batches_tracked", "Encoder_layer_4LFAatt_pooling_1fc.weight", "Encoder_layer_4LFAatt_pooling_1fc.bias", "Encoder_layer_4LFAatt_pooling_1mlp.biases", "Encoder_layer_4LFAatt_pooling_1mlp.weights", "Encoder_layer_4LFAatt_pooling_1mlp.conv.weight", "Encoder_layer_4LFAatt_pooling_1mlp.conv.bias", "Encoder_layer_4LFAatt_pooling_1mlp.batch_normalization.weight", "Encoder_layer_4LFAatt_pooling_1mlp.batch_normalization.bias", "Encoder_layer_4LFAatt_pooling_1mlp.batch_normalization.running_mean", "Encoder_layer_4LFAatt_pooling_1mlp.batch_normalization.running_var", "Encoder_layer_4LFAatt_pooling_1mlp.batch_normalization.num_batches_tracked", "Encoder_lay...
	size mismatch for fc0.weight: copying a param with shape torch.Size([8, 6]) from checkpoint, the shape in current model is torch.Size([8, 3]).
	size mismatch for decoder_0.biases: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for decoder_0.weights: copying a param with shape torch.Size([1024, 1024, 1, 1]) from checkpoint, the shape in current model is torch.Size([512, 512, 1, 1]).
	size mismatch for decoder_0.conv.weight: copying a param with shape torch.Size([1024, 1024, 1, 1]) from checkpoint, the shape in current model is torch.Size([512, 512, 1, 1]).
	size mismatch for decoder_0.conv.bias: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for decoder_0.batch_normalization.weight: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for decoder_0.batch_normalization.bias: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for decoder_0.batch_normalization.running_mean: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for decoder_0.batch_normalization.running_var: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for Decoder_layer_0.biases: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for Decoder_layer_0.weights: copying a param with shape torch.Size([1536, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([768, 256, 1, 1]).
	size mismatch for Decoder_layer_0.conv.weight: copying a param with shape torch.Size([1536, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([768, 256, 1, 1]).
	size mismatch for Decoder_layer_0.conv.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for Decoder_layer_0.batch_normalization.weight: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for Decoder_layer_0.batch_normalization.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for Decoder_layer_0.batch_normalization.running_mean: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for Decoder_layer_0.batch_normalization.running_var: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for Decoder_layer_1.biases: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for Decoder_layer_1.weights: copying a param with shape torch.Size([768, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([384, 128, 1, 1]).
	size mismatch for Decoder_layer_1.conv.weight: copying a param with shape torch.Size([768, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([384, 128, 1, 1]).
	size mismatch for Decoder_layer_1.conv.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for Decoder_layer_1.batch_normalization.weight: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for Decoder_layer_1.batch_normalization.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for Decoder_layer_1.batch_normalization.running_mean: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for Decoder_layer_1.batch_normalization.running_var: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for Decoder_layer_2.biases: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([32]).
	size mismatch for Decoder_layer_2.weights: copying a param with shape torch.Size([384, 128, 1, 1]) from checkpoint, the shape in current model is torch.Size([160, 32, 1, 1]).
	size mismatch for Decoder_layer_2.conv.weight: copying a param with shape torch.Size([384, 128, 1, 1]) from checkpoint, the shape in current model is torch.Size([160, 32, 1, 1]).
	size mismatch for Decoder_layer_2.conv.bias: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([32]).
	size mismatch for Decoder_layer_2.batch_normalization.weight: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([32]).
	size mismatch for Decoder_layer_2.batch_normalization.bias: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([32]).
	size mismatch for Decoder_layer_2.batch_normalization.running_mean: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([32]).
	size mismatch for Decoder_layer_2.batch_normalization.running_var: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([32]).
	size mismatch for Decoder_layer_3.weights: copying a param with shape torch.Size([160, 32, 1, 1]) from checkpoint, the shape in current model is torch.Size([64, 32, 1, 1]).
	size mismatch for Decoder_layer_3.conv.weight: copying a param with shape torch.Size([160, 32, 1, 1]) from checkpoint, the shape in current model is torch.Size([64, 32, 1, 1]).
	size mismatch for fc.biases: copying a param with shape torch.Size([8]) from checkpoint, the shape in current model is torch.Size([19]).
	size mismatch for fc.weights: copying a param with shape torch.Size([8, 32, 1, 1]) from checkpoint, the shape in current model is torch.Size([19, 32, 1, 1]).
	size mismatch for fc.conv.weight: copying a param with shape torch.Size([8, 32, 1, 1]) from checkpoint, the shape in current model is torch.Size([19, 32, 1, 1]).
	size mismatch for fc.conv.bias: copying a param with shape torch.Size([8]) from checkpoint, the shape in current model is torch.Size([19]).

**Comment by AmarR91** [comment]
Your input dimension is not compatible with the model dimension as you get the following error message:
size mismatch for fc0.weight: copying a param with shape torch.Size([8, 6]) from checkpoint, the shape in current model is torch.Size([8, 3]).

A possible way to fix this: #204
