### ISSUE TITLE
python requirements: Minimum versions for packages?

### ISSUE THREAD

**Issue by EricCousineau-TRI** [intel-isl/Open3D-ML#219]
Any chance y'all have minimum versions on these packages?

I'd like to use Ubuntu 18.04's current version of `scikit-learn` (apt: `python3-sklearn 0.19.1`), but I can't easily tell if it would work.

**Comment by EricCousineau-TRI** [comment]
Relates: https://github.com/intel-isl/Open3D/issues/2991

**Comment by germanros1987** [comment]
@sanskar107 could you please add the minimum versions?

**Comment by sanskar107** [comment]
@EricCousineau-TRI We have updated the minimum versions in `dev` branch which will be merged to master in the next release.

**Comment by sanskar107** [comment]
Fixed with the new release.
