### ISSUE TITLE
python requirements: plyfile is GPLv3 software, should be removed to remain MIT licensed?

### ISSUE THREAD

**Issue by EricCousineau-TRI** [intel-isl/Open3D-ML#220]
`plyfile` is GPL licensed; I would love to use your awesome library in our projects, but many users (myself included) are unable to incorporate GPL'd works into our projects, because we can't allow our own project to be governed by the GPL's terms.

Would you consider removing GPL'd dependencies from your requirements?

Information for `plyfile` in PyPi and it's latest release tag:
https://pypi.org/project/plyfile/
https://github.com/dranjan/python-plyfile/blob/v0.7.2/COPYING

From `pip-tools` (`pip-compile`):
https://gist.github.com/EricCousineau-TRI/ee119a3feeed77ac289ed06b01e587cc#file-requirements-txt-sh-L121-L122

Relates intel-isl/Open3D#2991

\cc @yxlao

**Comment by germanros1987** [comment]
We are working on fixing this. We understand the inconvenience.

**Comment by sanskar107** [comment]
@EricCousineau-TRI we have removed `plyfile` dependency from Open3D-ML. Currently the fix is in `dev` branch, which will be merged to master with the next release (within a month).

**Comment by EricCousineau-TRI** [comment]
That's awesome, thank you so much!

**Comment by sanskar107** [comment]
Fixed with the new release.
