### ISSUE TITLE
open3d 0.12.0 does not work in windows + conda env

### ISSUE THREAD

**Issue by charithmu** [intel-isl/Open3D-ML#232]
when installed using default steps in README.md (pip install open3d + tensorflow and/or pytorch),

It says the installed open3d package was not built with tensorflow or pytorch support.

python -c "import open3d.ml.tf as ml3d" --> Exception: Open3D was not built with TensorFlow support!
python -c "import open3d.ml.torch as ml3d" --> Exception: Open3D was not built with PyTorch support!

Found some old git issues (v.0.11.0) of complaining open3d windows package does not include open3d-ml as well?
Is there any issues with windows build scripts currently??

**Comment by sanskar107** [comment]
Hi @charithmu 
Unfortunately, windoes is not supported right now. You can try using windows subsystem for linux (WSL) to access the functionality on windows 10. We are trying to enable all features on windows, but there is no specific timeline yet.

**Comment by charithmu** [comment]
Thank you for the information. I guess I'll stick to linux for now as WSL + Cuda is also not very stable.
