### ISSUE TITLE
pipeline.run_inference(data) very slow

### ISSUE THREAD

**Issue by tvkpz** [intel-isl/Open3D-ML#234]
I am running inference using the the pre-trained KPConv implementation on a single example from the Toronto_3D dataset and the inference is very very slow. 

I am using an AWS p3.2xlarge with a V100 GPU. For some reason the GPU utilization is mostly zero. The code has high CPU utilization. Here is the code

```
import os
import open3d.ml as _ml3d
import open3d.ml.torch as ml3d

cfg_file = "../Open3D-ML/ml3d/configs/kpconv_toronto3d.yml"
cfg = _ml3d.utils.Config.load_from_file(cfg_file)

model = ml3d.models.KPFCNN(**cfg.model)
cfg.dataset['dataset_path'] = "../datasets/Toronto_3D"
dataset = ml3d.datasets.Toronto3D(cfg.dataset.pop('dataset_path', None), **cfg.dataset)
pipeline = ml3d.pipelines.SemanticSegmentation(model, dataset=dataset, device="gpu", **cfg.pipeline)

# download the weights.
ckpt_folder = "./logs/"
os.makedirs(ckpt_folder, exist_ok=True)
ckpt_path = ckpt_folder + "kpconv_toronto3d_202010081102utc.pth"
kpconv_url = "https://storage.googleapis.com/open3d-releases/model-zoo/kpconv_toronto3d_202010081102utc.pth"
if not os.path.exists(ckpt_path):
    cmd = "wget {} -O {}".format(kpconv_url, ckpt_path)
    os.system(cmd)

# load the parameters.
pipeline.load_ckpt(ckpt_path=ckpt_path)

test_split = dataset.get_split("test")
data = test_split.get_data(0)

# run inference on a single example.
# returns dict with 'predict_labels' and 'predict_scores'.
result = pipeline.run_inference(data) ### This step is very slow
```

**Comment by charithmu** [comment]
Try device="cuda"

**Comment by Hao-HUST** [comment]
> I am running inference using the the pre-trained KPConv implementation on a single example from the Toronto_3D dataset and the inference is very very slow.
> 
> I am using an AWS p3.2xlarge with a V100 GPU. For some reason the GPU utilization is mostly zero. The code has high CPU utilization. Here is the code
> 
> ```
> import os
> import open3d.ml as _ml3d
> import open3d.ml.torch as ml3d
> 
> cfg_file = "../Open3D-ML/ml3d/configs/kpconv_toronto3d.yml"
> cfg = _ml3d.utils.Config.load_from_file(cfg_file)
> 
> model = ml3d.models.KPFCNN(**cfg.model)
> cfg.dataset['dataset_path'] = "../datasets/Toronto_3D"
> dataset = ml3d.datasets.Toronto3D(cfg.dataset.pop('dataset_path', None), **cfg.dataset)
> pipeline = ml3d.pipelines.SemanticSegmentation(model, dataset=dataset, device="gpu", **cfg.pipeline)
> 
> # download the weights.
> ckpt_folder = "./logs/"
> os.makedirs(ckpt_folder, exist_ok=True)
> ckpt_path = ckpt_folder + "kpconv_toronto3d_202010081102utc.pth"
> kpconv_url = "https://storage.googleapis.com/open3d-releases/model-zoo/kpconv_toronto3d_202010081102utc.pth"
> if not os.path.exists(ckpt_path):
>     cmd = "wget {} -O {}".format(kpconv_url, ckpt_path)
>     os.system(cmd)
> 
> # load the parameters.
> pipeline.load_ckpt(ckpt_path=ckpt_path)
> 
> test_split = dataset.get_split("test")
> data = test_split.get_data(0)
> 
> # run inference on a single example.
> # returns dict with 'predict_labels' and 'predict_scores'.
> result = pipeline.run_inference(data) ### This step is very slow
> ```

Hi, you solved the problem?

**Comment by tvkpz** [comment]
Toronto3D point clouds are huge if you are using one of the test files. So it will take time. Check if it is doing preprocessing first. Probably that is the reason the inference is slow. Suggest you sample some points from a PCD and then try. You can also print the device being used from inside the code to check for GPU usage.

**Comment by AndreasGronlund** [comment]
I have the same problem (both randlanet and kpconv) with Kitti dataset. The problem is not the number of points or cuda being used. Another question, why is the ```pipelinerun_inference(data)``` method outputting a series of test results with IoU numbers and not just a single semantic classification output from the one data frame being inputted? I have seen others (not using open3d-ml) reporting over 20fps. Any ideas? Do I need to change the yml-file in some way?
