### ISSUE TITLE
Open3d ML support for Ubuntu 16.04

### ISSUE THREAD

**Issue by Hao-HUST** [intel-isl/Open3D-ML#253]
Hi, thank you for your great work.

Currently, Ubuntu 16.04 is not supported by Open3D-ML, even we try to compile the Open3D from the source code?

Do you have a plan to support Ubuntu 16.04 platform in the future?

**Comment by sanskar107** [comment]
@Hao-HUST Open3D is no longer supported on Ubuntu 16.04 as some of the libraries requires Ubuntu >= 18. You can try to compile from source and turn off GUI with `-DBUILD_GUI=OFF`.

**Comment by Hao-HUST** [comment]
Ok, thanks a lot!
