### ISSUE TITLE
`diff` varialble not defined

### ISSUE THREAD

**Issue by rakesh4real** [intel-isl/Open3D-ML#260]
https://github.com/intel-isl/Open3D-ML/blob/master/ml3d/datasets/samplers/semseg_spatially_regular.py#L86

**Comment by rakesh4real** [comment]
https://github.com/intel-isl/Open3D-ML/blob/master/ml3d/datasets/samplers/semseg_spatially_regular.py#L86

**Comment by eiiijiiiy** [comment]
use this may work
`diff = num_points - pc.shape[0]`
Just a temporary solution

**Comment by accelaire** [comment]
See issue #250 guys

**Comment by sanskar107** [comment]
Copy of #250
