### ISSUE TITLE
Semantic Segmentation Test Error

### ISSUE THREAD

**Issue by juan3299** [intel-isl/Open3D-ML#261]
Hello, 
Thanks for your great job doing this library.

Here is my Issue
I've create a custom dataset, using Custom3D format
I've managed to train a RANLANET for a semantic segmentation using "run_pipeline.py" scripy using my own custom config file.

After training the network, I tried to test the network with my test dataset, but it failed

This is the error:
![error](https://user-images.githubusercontent.com/83212233/116217853-44e1cf80-a74a-11eb-93ed-231919ae2117.png)

I don't know if my dataset is wrong, or my config file is wrong or is a bug.

Thanks for your help

**Comment by sanskar107** [comment]
@juan3299  If you are using Custom3D dataset, you have to define your `save_test_result` method in `ml3d/datasets/customdataset.py`.

**Comment by sanskar107** [comment]
@juan3299  feel free to close this issue if it works.
