### ISSUE TITLE
fine tuning after loading the semanticKitti checkpoint class number issue

### ISSUE THREAD

**Issue by samux87** [intel-isl/Open3D-ML#277]
Hi guys, 

I would like to load the semanticKitti checkpoint and finetune with a new dataset.

I noticed that I must set the same num_classes: 19 in the .yml in order to load the semanticKitti checkpoint, but I would like to finetune only on 2 classes; is it possible?

Thank you,
Sam.

**Comment by sanskar107** [comment]
@samux87 It is possible, there are two ways:
1) You can manually customise weight loading for the last layer.
2) You can keep num_classes as 19 but and customise loss function such that softmax is applied only to those two classes and ignore other classes.

**Comment by samux87** [comment]
Thank you @sanskar107! 

Both options look good.
I would like to follow the first option first; Can you help me identify where I need to modify the code?

I think we have to modify semantic_segmentation.py or randlanet.py for that right?

Thank you,
Sam.

**Comment by sanskar107** [comment]
You don't need to change any code. You can write a script which loads weight file and manually slice the weights for last layer such that it corresponds to the classes you want.
for e.g., if the shape of last layer is `[N, 19]`, you can extract those two columns which corresponds to your class.

**Comment by samux87** [comment]
oh ok! I never did this so I am trying to translate what you said with my knowledge.

Maybe I could create that script that:
- load the pretreated checkpoint/weights 
`checkpoint = torch.load(weights_path)`
- modify the dict selecting the classes needed (idk how to do this yet)
- save the modified dict and use that for training
`torch.save(model.state_dict(), save_path)`

I started to explore the dict and I found that is long 4 this is the output:

first:
`{'param_groups': [{'betas': (0.9, 0.999),
   'weight_decay': 0,
   'amsgrad': False,
   'eps': 1e-08,
   'initial_lr': 0.01,
   'lr': 0.01,
   'params': [139743557399320,
    139743557399392,
    139743557399464,
    139743557399536,
    139743557399896,
    139743557399824,
    139743557399968,
    139743557400040,
    139743557400544,
    139743557400472,
    139743557400616,
    139743557400688,
    139743557401048,
    139743557401120,
    139743557401264,
    139743557401192,
    139743557401336,
    139743557401408,
    139743557401768,
    139743557401696,
    139743557401840,
    139743557401912,
    139743557402272,
    139743557402344,
    139743557402488,
    139743557402416,
    139743557402560,
    139743557521480,
    139743557521768,
    139743557521696,
    139743557521840,
    139743557521912,
    139743557522344,
    139743557522272,
    139743557522416,
    139743557522488,
    139743557522920,
    139743557522848,
    139743557522992,
    139743557523064,
    139743557523568,
    139743557523496,
    139743557523640,
    139743557523712,
    139743557524072,
    139743557524144,
    139743557524288,
    139743557524216,
    139743557524360,
    139743557524432,
    139743557524792,
    139743557524720,
    139743557524864,
    139743557524936,
    139743557525296,
    139743557525368,
    139743557566536,
    139743557525440,
    139743557566608,
    139743557566680,
    139743557566968,
    139743557566896,
    139743557567040,
    139743557567112,
    139743557567544,
    139743557567472,
    139743557567616,
    139743557567688,
    139743557568120,
    139743557568048,
    139743557568192,
    139743557568264,
    139743557568768,
    139743557568696,
    139743557568840,
    139743557568912,
    139743557569272,
    139743557569344,
    139743557569488,
    139743557569416,
    139743557569560,
    139743557569632,
    139743557569992,
    139743557569920,
    139743557570064,
    139743557570136,
    139743557570496,
    139743557099592,
    139743557099736,
    139743557099664,
    139743557099808,
    139743557099880,
    139743557100168,
    139743557100096,
    139743557100240,
    139743557100312,
    139743557100744,
    139743557100672,
    139743557100816,
    139743557100888,
    139743557101320,
    139743557101248,
    139743557101392,
    139743557101464,
    139743557101968,
    139743557101896,
    139743557102040,
    139743557102112,
    139743557102472,
    139743557102544,
    139743557102688,
    139743557102616,
    139743557102760,
    139743557102832,
    139743557103192,
    139743557103120,
    139743557103264,
    139743557103336,
    139743557152912,
    139743557152984,
    139743557153128,
    139743557153056,
    139743557153200,
    139743557153272,
    139743557153560,
    139743557153488,
    139743557153632,
    139743557153704,
    139743557154136,
    139743557154064,
    139743557154208,
    139743557154280,
    139743557154712,
    139743557154640,
    139743557154784,
    139743557154856,
    139743557155216,
    139743557155144,
    139743557155288,
    139743557155360,
    139743557155720,
    139743557155648,
    139743557155792,
    139743557155864,
    139743557156224,
    139743557156152,
    139743557156296,
    139743557156368,
    139743557156728,
    139743557156656,
    139743557156800,
    139743557210184,
    139743557210544,
    139743557210472,
    139743557210616,
    139743557210688,
    139743557211048,
    139743557210976,
    139743557211120,
    139743557211192,
    139743557211552,
    139743557211480]}],
 'state': {}}`

second:
`{'_last_lr': [0.01],
 'gamma': 0.95,
 'base_lrs': [0.01],
 'last_epoch': 0,
 '_get_lr_called_within_step': False,
 '_step_count': 1}`
third:
`0`
fourth:
`[[-1.7210]],
              
                       [[-2.5510]],
              
                       [[ 0.5977]],
              
                       [[-2.3732]],
              
                       [[-1.0403]],
              
                       [[-1.8449]],
              
                       [[-1.4375]],
              
                       [[-0.9165]],
              
                       [[ 0.9290]],
              
                       [[-0.9637]],
              
                       [[ 0.9020]],
              
                       [[-1.7473]],
              
                       [[-1.8069]],
              
                       [[-1.5651]],
              
                       [[-2.0630]],
              
                       [[ 0.8180]],
              
                       [[-2.3045]],
              
                       [[-2.4260]],
              
                       [[-2.0739]],
              
                       [[-2.2623]],
              
                       [[ 0.7673]],
              
                       [[ 1.0118]],
              
                       [[-0.8475]],
              
                       [[-2.7479]],
              
                       [[-2.1551]],
              
                       [[-0.5814]],
              
                       [[-1.9743]],
              
                       [[-1.5670]],
              
                       [[-2.6823]],
              
                       [[-2.1370]],
              
                       [[-1.6283]]],
              
              
                      [[[ 1.3152]],
              
                       [[-1.2795]],
              
                       [[-2.0042]],
              
                       [[ 0.9402]],
              
                       [[-2.3524]],
              
                       [[-1.7912]],
              
                       [[-1.1258]],
              
                       [[ 1.0703]],
              
                       [[-1.5602]],
              
                       [[ 1.2062]],
              
                       [[-1.6465]],
              
                       [[ 1.1062]],
              
                       [[ 0.9515]],
              
                       [[ 0.9652]],
              
                       [[-0.7762]],
              
                       [[-1.8043]],
              
                       [[ 1.1102]],
              
                       [[-1.2804]],
              
                       [[ 0.9248]],
              
                       [[-1.5903]],
              
                       [[-1.2689]],
              
                       [[ 0.6516]],
              
                       [[ 1.0414]],
              
                       [[ 0.9593]],
              
                       [[-2.2368]],
              
                       [[ 0.9799]],
              
                       [[ 1.0579]],
              
                       [[ 0.7584]],
              
                       [[-0.8036]],
              
                       [[ 0.7759]],
              
                       [[-1.7253]],
              
                       [[-0.7728]]],
              
              
                      [[[ 1.2712]],
              
                       [[-1.3052]],
              
                       [[ 0.6818]],
              
                       [[ 0.9170]],
              
                       [[ 0.4031]],
              
                       [[-1.7973]],
              
                       [[-1.2403]],
              
                       [[ 0.9553]],
              
                       [[ 0.6578]],
              
                       [[ 1.1218]],
              
                       [[-1.6781]],
              
                       [[-1.2306]],
              
                       [[ 0.8401]],
              
                       [[ 0.9658]],
              
                       [[-0.8552]],
              
                       [[-1.8500]],
              
                       [[ 1.0853]],
              
                       [[ 1.1991]],
              
                       [[-1.7349]],
              
                       [[-1.6079]],
              
                       [[-1.3324]],
              
                       [[-2.1474]],
              
                       [[-1.4279]],
              
                       [[-1.7325]],
              
                       [[ 0.6255]],
              
                       [[-1.3401]],
              
                       [[ 1.0126]],
              
                       [[-1.5660]],
              
                       [[-0.8754]],
              
                       [[-2.0922]],
              
                       [[-1.7542]],
              
                       [[-0.8653]]],
              
              
                      [[[ 0.9588]],
              
                       [[-1.2121]],
              
                       [[ 0.5540]],
              
                       [[ 0.7988]],
              
                       [[-2.1431]],
              
                       [[-1.6092]],
              
                       [[ 1.2088]],
              
                       [[-0.9175]],
              
                       [[-1.3875]],
              
                       [[ 0.0298]],
              
                       [[-1.5049]],
              
                       [[ 1.0086]],
              
                       [[-1.0777]],
              
                       [[ 0.9113]],
              
                       [[ 1.1399]],
              
                       [[-1.7252]],
              
                       [[ 1.0092]],
              
                       [[ 1.1446]],
              
                       [[-1.4723]],
              
                       [[-1.4512]],
              
                       [[ 1.2044]],
              
                       [[-1.7623]],
              
                       [[-1.1595]],
              
                       [[ 0.9056]],
              
                       [[-1.9801]],
              
                       [[ 0.8922]],
              
                       [[ 0.9391]],
              
                       [[ 0.6275]],
              
                       [[ 1.2050]],
              
                       [[-1.8000]],
              
                       [[-1.6266]],
              
                       [[ 1.1461]]],
              
              
                      [[[-1.3633]],
              
                       [[-1.2318]],
              
                       [[-2.1578]],
              
                       [[-2.1994]],
              
                       [[-2.3613]],
              
                       [[ 0.8750]],
              
                       [[-1.1165]],
              
                       [[ 0.9767]],
              
                       [[-1.6369]],
              
                       [[-1.3856]],
              
                       [[-1.7351]],
              
                       [[-1.5057]],
              
                       [[ 0.8606]],
              
                       [[-1.3808]],
              
                       [[ 1.2515]],
              
                       [[-1.8065]],
              
                       [[ 0.8848]],
              
                       [[-1.2087]],
              
                       [[ 0.9574]],
              
                       [[ 0.8181]],
              
                       [[ 1.2245]],
              
                       [[-2.3954]],
              
                       [[ 0.8868]],
              
                       [[-1.6982]],
              
                       [[-2.2581]],
              
                       [[ 0.9286]],
              
                       [[ 0.9321]],
              
                       [[ 0.6444]],
              
                       [[ 1.2689]],
              
                       [[ 0.7610]],
              
                       [[ 1.1640]],
              
                       [[ 1.2557]]],
              
              
                      [[[-1.3848]],
              
                       [[ 1.3519]],
              
                       [[ 0.6112]],
              
                       [[-2.5198]],
              
                       [[ 0.8068]],
              
                       [[ 0.9258]],
              
                       [[-0.9214]],
              
                       [[-1.2968]],
              
                       [[-1.5142]],
              
                       [[-1.3723]],
              
                       [[-1.2491]],
              
                       [[-1.3436]],
              
                       [[-1.6107]],
              
                       [[ 0.9170]],
              
                       [[ 1.2242]],
              
                       [[ 1.0616]],
              
                       [[-2.1839]],
              
                       [[-1.3214]],
              
                       [[ 0.9544]],
              
                       [[-1.6294]],
              
                       [[-1.2568]],
              
                       [[-2.3500]],
              
                       [[-1.3425]],
              
                       [[ 1.0420]],
              
                       [[ 0.7716]],
              
                       [[ 0.9521]],
              
                       [[-1.7199]],
              
                       [[-1.9430]],
              
                       [[ 1.2138]],
              
                       [[ 0.5199]],
              
                       [[ 1.2781]],
              
                       [[ 1.1979]]],
              
              
                      [[[-0.9379]],
              
                       [[-0.7439]],
              
                       [[ 0.4729]],
              
                       [[-2.1550]],
              
                       [[ 0.5210]],
              
                       [[ 0.8281]],
              
                       [[ 1.2293]],
              
                       [[-1.0899]],
              
                       [[ 0.7647]],
              
                       [[-1.0298]],
              
                       [[ 0.9505]],
              
                       [[ 0.9292]],
              
                       [[-1.3756]],
              
                       [[-1.1005]],
              
                       [[ 1.1578]],
              
                       [[ 0.9699]],
              
                       [[-1.9073]],
              
                       [[ 1.1648]],
              
                       [[ 0.8282]],
              
                       [[ 0.7015]],
              
                       [[ 1.2161]],
              
                       [[ 0.4674]],
              
                       [[-1.1878]],
              
                       [[-1.0457]],
              
                       [[ 0.6605]],
              
                       [[-0.8329]],
              
                       [[ 0.7891]],
              
                       [[-1.7133]],
              
                       [[ 1.1527]],
              
                       [[ 0.5934]],
              
                       [[ 1.1914]],
              
                       [[ 1.1634]]],
              
              
                      [[[ 1.0709]],
              
                       [[ 1.2569]],
              
                       [[-1.4581]],
              
                       [[-2.4314]],
              
                       [[ 0.7270]],
              
                       [[ 0.8013]],
              
                       [[ 1.1957]],
              
                       [[ 0.6913]],
              
                       [[ 0.7273]],
              
                       [[ 0.9959]],
              
                       [[ 0.9211]],
              
                       [[-0.9260]],
              
                       [[ 0.5602]],
              
                       [[ 0.7088]],
              
                       [[-0.5185]],
              
                       [[ 0.9011]],
              
                       [[-2.0946]],
              
                       [[ 1.1314]],
              
                       [[ 0.9395]],
              
                       [[ 0.6439]],
              
                       [[ 1.1873]],
              
                       [[ 0.4529]],
              
                       [[ 0.8491]],
              
                       [[ 0.7968]],
              
                       [[ 0.6116]],
              
                       [[ 0.7842]],
              
                       [[-1.5122]],
              
                       [[-1.6948]],
              
                       [[-0.5208]],
              
                       [[ 0.5198]],
              
                       [[ 1.2662]],
              
                       [[-0.5557]]],
              
              
                      [[[ 1.2430]],
              
                       [[ 1.4137]],
              
                       [[-2.1085]],
              
                       [[-2.5417]],
              
                       [[ 0.8303]],
              
                       [[-1.3836]],
              
                       [[ 1.2590]],
              
                       [[-1.2138]],
              
                       [[-1.3036]],
              
                       [[ 1.2104]],
              
                       [[ 1.0939]],
              
                       [[-1.3101]],
              
                       [[-1.5457]],
              
                       [[-1.2363]],
              
                       [[-0.8379]],
              
                       [[ 1.0981]],
              
                       [[-2.1855]],
              
                       [[-1.2544]],
              
                       [[ 1.0005]],
              
                       [[-1.4306]],
              
                       [[-1.2758]],
              
                       [[-1.9452]],
              
                       [[ 1.0364]],
              
                       [[-1.3953]],
              
                       [[-1.9864]],
              
                       [[-1.2699]],
              
                       [[-1.7775]],
              
                       [[ 0.5930]],
              
                       [[-0.9374]],
              
                       [[-2.0452]],
              
                       [[ 1.3650]],
              
                       [[-0.9145]]],
              
              
                      [[[ 1.2440]],
              
                       [[ 1.2336]],
              
                       [[-1.7739]],
              
                       [[ 0.6657]],
              
                       [[-2.0855]],
              
                       [[-1.5102]],
              
                       [[ 1.1575]],
              
                       [[ 0.9078]],
              
                       [[ 0.7609]],
              
                       [[ 1.1516]],
              
                       [[ 0.8993]],
              
                       [[-1.0291]],
              
                       [[ 0.7961]],
              
                       [[-1.0558]],
              
                       [[ 1.1917]],
              
                       [[ 0.9476]],
              
                       [[ 0.8002]],
              
                       [[ 1.1048]],
              
                       [[-1.3825]],
              
                       [[ 0.6638]],
              
                       [[ 1.1296]],
              
                       [[-1.8839]],
              
                       [[-1.2766]],
              
                       [[ 0.9072]],
              
                       [[-2.0057]],
              
                       [[ 0.9026]],
              
                       [[-1.3832]],
              
                       [[ 0.6072]],
              
                       [[-0.6991]],
              
                       [[-1.7778]],
              
                       [[ 1.1714]],
              
                       [[ 1.1931]]],
              
              
                      [[[-1.5708]],
              
                       [[ 1.3939]],
              
                       [[-1.9100]],
              
                       [[-2.6471]],
              
                       [[ 0.9109]],
              
                       [[-1.7181]],
              
                       [[-0.6982]],
              
                       [[-1.2553]],
              
                       [[ 0.8598]],
              
                       [[ 1.0924]],
              
                       [[ 0.8544]],
              
                       [[ 1.0569]],
              
                       [[-1.5537]],
              
                       [[-1.2926]],
              
                       [[ 1.1553]],
              
                       [[-1.4231]],
              
                       [[-2.2834]],
              
                       [[ 1.1024]],
              
                       [[ 1.0541]],
              
                       [[-1.7824]],
              
                       [[ 1.1521]],
              
                       [[ 0.7083]],
              
                       [[-0.8333]],
              
                       [[-1.3713]],
              
                       [[-1.8561]],
              
                       [[-1.2504]],
              
                       [[-1.8159]],
              
                       [[ 0.6764]],
              
                       [[ 1.2538]],
              
                       [[-2.3424]],
              
                       [[ 1.3499]],
              
                       [[-1.1045]]],
              
              
                      [[[-1.7669]],
              
                       [[ 1.4723]],
              
                       [[ 0.4581]],
              
                       [[-2.7333]],
              
                       [[ 0.9742]],
              
                       [[-1.8773]],
              
                       [[ 0.8897]],
              
                       [[-1.3181]],
              
                       [[ 0.9744]],
              
                       [[-0.9138]],
              
                       [[-1.2792]],
              
                       [[ 1.1533]],
              
                       [[-1.5561]],
              
                       [[-1.4751]],
              
                       [[-0.6669]],
              
                       [[-1.5994]],
              
                       [[-2.3690]],
              
                       [[-0.7328]],
              
                       [[ 1.1146]],
              
                       [[-1.9401]],
              
                       [[-0.6373]],
              
                       [[ 0.8485]],
              
                       [[ 0.9513]],
              
                       [[-1.4634]],
              
                       [[ 0.5775]],
              
                       [[-1.3366]],
              
                       [[-1.9697]],
              
                       [[-1.4542]],
              
                       [[-0.6619]],
              
                       [[-2.5015]],
              
                       [[ 1.4162]],
              
                       [[-1.2907]]]], device='cuda:0')),
             ('fc.conv.bias',
              tensor([-0.3394, -2.1227, -2.5052, -2.7022, -1.2575, -2.1784, -4.5136, -7.2328,
                      -0.3608, -0.0170,  1.3825, -0.4102,  0.4078,  1.4013,  1.5561, -0.7008,
                       1.3180, -0.6221, -2.6389], device='cuda:0'))])`

At this point, is it the last "fc.conv.bias" tensor that I need to slice?

Thank you,
Sam.

**Comment by samux87** [comment]
I did this and now I don't have errors when loading the checkpoint (IDK if is it correct xD):

`
import torch 
import numpy as np

weights_path = '/media/sam/grosso/OneDrive/ML/pointNet/vis_weights_RandLANet.pth'
save_path = '/media/sam/grosso/OneDrive/ML/pointNet/vis_weights_RandLANet_MOD.pth'

# load weights as it is
checkpoint = torch.load(weights_path)

# mod dict selecting the classes needed (0 and 9 class)

copia = checkpoint
copia['model_state_dict']['fc.biases'] = checkpoint['model_state_dict']['fc.biases'][np.r_[0,9]]
copia['model_state_dict']['fc.weights'] = checkpoint['model_state_dict']['fc.weights'][np.r_[0,9]]
copia['model_state_dict']['fc.conv.weight'] = checkpoint['model_state_dict']['fc.conv.weight'][np.r_[0,9]]
copia['model_state_dict']['fc.conv.bias'] = checkpoint['model_state_dict']['fc.conv.bias'][np.r_[0,9]]

nuovo = dict(epoch=checkpoint['epoch'],
             model_state_dict=copia['model_state_dict'],
             optimizer_state_dict=checkpoint['optimizer_state_dict'],
             scheduler_state_dict=checkpoint['scheduler_state_dict'])

# save mod dict
torch.save(nuovo, save_path)

print('FINE')
`

**Comment by sanskar107** [comment]
@samux87 yes this looks correct.

**Comment by samux87** [comment]
Ok, thank you again.

**Comment by eliasm56** [comment]
Hi @samux87,

This solution will help me as I am about to attempt fine-tuning RandLA-Net (pretrained on S3DIS) with my own custom dataset. I have one question regarding your solution: Did you change num of classes in the config file AND modify the model weights, or did you leave the num of classes as it is and ONLY modify model weights? I will try it out anyway and see for myself.

Best,
Elias

**Comment by eliasm56** [comment]
@samux87 

Sorry to bother you, but do you mind providing your code, or further elaborating on how you managed to customize weight loading on the last layer of RandLA-Net? I tried to replicate your solution as you have shown above, but I cannot quite figure out the implementation.

Thanks,
Elias
