### ISSUE TITLE
class_weights conf file information

### ISSUE THREAD

**Issue by samux87** [intel-isl/Open3D-ML#278]
Hi guys,

what is the class_weights in the semanticKitti dataset .yml?

is it a points count for each class all over the point clouds of the dataset?

Thank youuuuu,
Sam.

**Comment by samux87** [comment]
Just found this: 
https://www.analyticsvidhya.com/blog/2020/10/improve-class-imbalance-class-weights/

Is there any way to set the class weights "balanced" or maybe calculate these weights automatically?

Thank you,
Sam.

**Comment by sanskar107** [comment]
@samux87 the weights in config files are sum of points in each class over training set. If you want to experiment with different class weights, you can manually change them in config file.

**Comment by samux87** [comment]
Ok, thank you for the info!
