### ISSUE TITLE
AttributeError: 'open3d.cuda.pybind.visualization.gui.LayoutContext' object has no attribute 'font_size'

### ISSUE THREAD

**Issue by yucedagonurcan** [intel-isl/Open3D-ML#281]
Hello All,

First of all, thank you for this project.

I have just started learning Open3D and Open3D-ML and after building I tried the examples that includes pytorch such as: [vis_pred.py](https://github.com/intel-isl/Open3D-ML/blob/master/examples/vis_pred.py)

But I have this error after execution: 

> 
>   File "vis_pred.py", line 120, in <module>
>     main()
>   File "vis_pred.py", line 116, in main
>     v.visualize(pcs_with_pred)
>   File "/home/onur/Development/open_env/lib/python3.6/site-packages/open3d/_ml3d/vis/visualizer.py", line 1575, in visualize
>     self._visualize("Open3D", width, height)
>   File "/home/onur/Development/open_env/lib/python3.6/site-packages/open3d/_ml3d/vis/visualizer.py", line 1620, in _visualize
>     gui.Application.instance.run()
>   File "/home/onur/Development/open_env/lib/python3.6/site-packages/open3d/_ml3d/vis/visualizer.py", line 1306, in _on_layout
>     em = theme.font_size
> AttributeError: 'open3d.cuda.pybind.visualization.gui.LayoutContext' object has no attribute 'font_size'

- Temporarily, I changed the Line 1306 of /home/onur/Development/Open3D-ML/examples/visualize.py:

   - From: 
       ![before](https://user-images.githubusercontent.com/16342629/119228910-f5f74200-bb1d-11eb-958e-36d601ab0c52.png)
   - To:
       ![after](https://user-images.githubusercontent.com/16342629/119228917-fdb6e680-bb1d-11eb-897c-761ed44124a9.png)

What am I missing here? How can I resolve this permanently?

My system:

CUDA: 11.1
DRIVER: 460

Open3D: From source 
Open3D 0.12.0 Configuration Summary
================================================================================
Enabled Features:

>   OpenMP .................................. ON
>   Headless Rendering ...................... OFF
>   Azure Kinect Support .................... OFF
>   Intel RealSense Support ................. OFF
>   CUDA Support ............................ ON
>   Build GUI ............................... ON
>   Build WebRTC visualizer ................. ON
>   Build Shared Library .................... OFF
>   Build Unit Tests ........................ OFF
>   Build Examples .......................... ON
>   Build Python Module ..................... ON
>   Build Jupyter Extension ................. OFF
>   Build TensorFlow Ops .................... OFF
>   Build PyTorch Ops ....................... ON
>   Build Benchmarks ........................ OFF
>   Bundle Open3D-ML ........................ ON
>   Build RPC interface ..................... OFF
>   Force GLIBCXX_USE_CXX11_ABI= ............ 0

**Comment by yucedagonurcan** [comment]
I will try the dev branch: https://github.com/intel-isl/Open3D-ML/commit/bf26433e1eec79aa71c63bba7888a18a2824fe30#diff-52a606587ca2875f22f947877308303a4b41cb24cf0a839a2630bb1f13bafa01

**Comment by yucedagonurcan** [comment]
Now it crashes for some other reason: 
I added      `   GIT_TAG "dev" ` to pybind's CMakeLists.txt so that I changed my ml package branch. Here is what I am getting running the same python demo script, vis_pred.py:


> Traceback (most recent call last):
>   File "vis_pred.py", line 120, in <module>
>     main()
>   File "vis_pred.py", line 114, in main
>     pcs_with_pred = pred_custom_data(pc_names, pcs, pipeline_r, pipeline_k)
>   File "vis_pred.py", line 45, in pred_custom_data
>     results_k = pipeline_k.run_inference(data)
>   File "/home/onur/Development/open_env/lib/python3.6/site-packages/open3d/_ml3d/torch/pipelines/semantic_segmentation.py", line 168, in run_inference
>     for step, inputs in enumerate(infer_loader):
>   File "/home/onur/Development/open_env/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
>     data = self._next_data()
>   File "/home/onur/Development/open_env/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 557, in _next_data
>     data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
>   File "/home/onur/Development/open_env/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
>     return self.collate_fn(data)
>   File "/home/onur/Development/open_env/lib/python3.6/site-packages/open3d/_ml3d/torch/dataloaders/concat_batcher.py", line 532, in collate_fn
>     f"Please define collate_fn for {self.model}, or use Default Batcher"
> Exception: Please define collate_fn for KPFCNN, or use Default Batcher
>

**Comment by sanskar107** [comment]
@yucedagonurcan thanks for reporting this. The name of KPConv model is `KPFCNN` while `KPConv` is being used in the batcher. As a workaround you can just change the name of your mode. Feel free to create a pull request for this fix.
